services:
  text-to-handwriting:
    build: .
    container_name: text-to-handwriting-app
    volumes:
      - ./output:/app/output
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    working_dir: /app
